// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToShelf(arg1, arg2) {
  return window['go']['backend']['App']['AddToShelf'](arg1, arg2);
}

export function AlgoFilter(arg1) {
  return window['go']['backend']['App']['AlgoFilter'](arg1);
}

export function AlgoProduct(arg1) {
  return window['go']['backend']['App']['AlgoProduct'](arg1);
}

export function ArticleDetail(arg1, arg2) {
  return window['go']['backend']['App']['ArticleDetail'](arg1, arg2);
}

export function ArticleList(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['App']['ArticleList'](arg1, arg2, arg3, arg4, arg5);
}

export function ArticleListAll(arg1, arg2) {
  return window['go']['backend']['App']['ArticleListAll'](arg1, arg2);
}

export function AudioDetail(arg1) {
  return window['go']['backend']['App']['AudioDetail'](arg1);
}

export function AudioDetailAlias(arg1) {
  return window['go']['backend']['App']['AudioDetailAlias'](arg1);
}

export function BatchCourseDownload(arg1, arg2) {
  return window['go']['backend']['App']['BatchCourseDownload'](arg1, arg2);
}

export function BatchEbookDownload(arg1, arg2) {
  return window['go']['backend']['App']['BatchEbookDownload'](arg1, arg2);
}

export function BatchOdobDownload(arg1, arg2) {
  return window['go']['backend']['App']['BatchOdobDownload'](arg1, arg2);
}

export function ChannelHomepage(arg1) {
  return window['go']['backend']['App']['ChannelHomepage'](arg1);
}

export function ChannelInfo(arg1) {
  return window['go']['backend']['App']['ChannelInfo'](arg1);
}

export function ChannelTopicDetail(arg1) {
  return window['go']['backend']['App']['ChannelTopicDetail'](arg1);
}

export function ChannelVipInfo(arg1) {
  return window['go']['backend']['App']['ChannelVipInfo'](arg1);
}

export function CheckLogin(arg1, arg2) {
  return window['go']['backend']['App']['CheckLogin'](arg1, arg2);
}

export function CourseCategory() {
  return window['go']['backend']['App']['CourseCategory']();
}

export function CourseDownload(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['CourseDownload'](arg1, arg2, arg3, arg4);
}

export function CourseGroupList(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['backend']['App']['CourseGroupList'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CourseInfo(arg1) {
  return window['go']['backend']['App']['CourseInfo'](arg1);
}

export function CourseList(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['App']['CourseList'](arg1, arg2, arg3, arg4, arg5);
}

export function EbookCommentList(arg1, arg2, arg3) {
  return window['go']['backend']['App']['EbookCommentList'](arg1, arg2, arg3);
}

export function EbookDownload(arg1, arg2, arg3) {
  return window['go']['backend']['App']['EbookDownload'](arg1, arg2, arg3);
}

export function EbookInfo(arg1) {
  return window['go']['backend']['App']['EbookInfo'](arg1);
}

export function EbookShelfAdd(arg1) {
  return window['go']['backend']['App']['EbookShelfAdd'](arg1);
}

export function EbookShelfRemove(arg1) {
  return window['go']['backend']['App']['EbookShelfRemove'](arg1);
}

export function EbookUserInfo() {
  return window['go']['backend']['App']['EbookUserInfo']();
}

export function GetArticleIntro(arg1, arg2) {
  return window['go']['backend']['App']['GetArticleIntro'](arg1, arg2);
}

export function GetHomeInitialState() {
  return window['go']['backend']['App']['GetHomeInitialState']();
}

export function GetNavbar() {
  return window['go']['backend']['App']['GetNavbar']();
}

export function GetQrcode() {
  return window['go']['backend']['App']['GetQrcode']();
}

export function GetActiveUser() {
  return window['go']['backend']['App']['GetActiveUser']();
}

export function GetDownloadPath() {
  return window['go']['backend']['App']['GetDownloadPath']();
}

export function GetSettings() {
  return window['go']['backend']['App']['GetSettings']();
}

export function SaveSettings(arg1) {
  return window['go']['backend']['App']['SaveSettings'](arg1);
}

export function GetVolcPlayAuthToken(arg1, arg2) {
  return window['go']['backend']['App']['GetVolcPlayAuthToken'](arg1, arg2);
}

export function GetVolcPlayInfo(arg1) {
  return window['go']['backend']['App']['GetVolcPlayInfo'](arg1);
}

export function HallCacheStatus() {
  return window['go']['backend']['App']['HallCacheStatus']();
}

export function HallSearch(arg1, arg2) {
  return window['go']['backend']['App']['HallSearch'](arg1, arg2);
}

export function Logout() {
  return window['go']['backend']['App']['Logout']();
}

export function NotesTimeline(arg1) {
  return window['go']['backend']['App']['NotesTimeline'](arg1);
}

export function OdobDownload(arg1, arg2, arg3) {
  return window['go']['backend']['App']['OdobDownload'](arg1, arg2, arg3);
}

export function OdobShelfAdd(arg1) {
  return window['go']['backend']['App']['OdobShelfAdd'](arg1);
}

export function OdobUserInfo() {
  return window['go']['backend']['App']['OdobUserInfo']();
}

export function OnSecondInstanceLaunch(arg1) {
  return window['go']['backend']['App']['OnSecondInstanceLaunch'](arg1);
}

export function OpenDirectoryDialog(arg1) {
  return window['go']['backend']['App']['OpenDirectoryDialog'](arg1);
}

export function OpenFileDialog(arg1) {
  return window['go']['backend']['App']['OpenFileDialog'](arg1);
}

export function OpenLoginBrowser() {
  return window['go']['backend']['App']['OpenLoginBrowser']();
}

export function OutsideDetail(arg1) {
  return window['go']['backend']['App']['OutsideDetail'](arg1);
}

export function PhoneLogin(arg1, arg2, arg3) {
  return window['go']['backend']['App']['PhoneLogin'](arg1, arg2, arg3);
}

export function ProductInfo(arg1) {
  return window['go']['backend']['App']['ProductInfo'](arg1);
}

export function RefreshHallCache() {
  return window['go']['backend']['App']['RefreshHallCache']();
}

export function RemoveFromShelf(arg1, arg2) {
  return window['go']['backend']['App']['RemoveFromShelf'](arg1, arg2);
}

export function SearchAll(arg1, arg2, arg3) {
  return window['go']['backend']['App']['SearchAll'](arg1, arg2, arg3);
}

export function SearchCourse(arg1, arg2, arg3) {
  return window['go']['backend']['App']['SearchCourse'](arg1, arg2, arg3);
}

export function SearchHot() {
  return window['go']['backend']['App']['SearchHot']();
}

export function SearchProducts(arg1, arg2) {
  return window['go']['backend']['App']['SearchProducts'](arg1, arg2);
}

export function SearchProductsByType(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['SearchProductsByType'](arg1, arg2, arg3, arg4);
}

export function SendPhoneCode(arg1) {
  return window['go']['backend']['App']['SendPhoneCode'](arg1);
}

export function SendPhoneCodeWithCaptcha(arg1, arg2) {
  return window['go']['backend']['App']['SendPhoneCodeWithCaptcha'](arg1, arg2);
}

export function SetDir(arg1) {
  return window['go']['backend']['App']['SetDir'](arg1);
}

export function SetDownloadPath(arg1) {
  return window['go']['backend']['App']['SetDownloadPath'](arg1);
}

export function SunflowerLabelContent(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['SunflowerLabelContent'](arg1, arg2, arg3, arg4);
}

export function SunflowerLabelList(arg1) {
  return window['go']['backend']['App']['SunflowerLabelList'](arg1);
}

export function SunflowerResourceList() {
  return window['go']['backend']['App']['SunflowerResourceList']();
}

export function TopicAll(arg1, arg2) {
  return window['go']['backend']['App']['TopicAll'](arg1, arg2);
}

export function TopicNoteDetail(arg1) {
  return window['go']['backend']['App']['TopicNoteDetail'](arg1);
}

export function TopicNotesList(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['TopicNotesList'](arg1, arg2, arg3, arg4);
}

export function UserInfo() {
  return window['go']['backend']['App']['UserInfo']();
}
